version: "3"
services:
  web:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${PROJECT_PATH}:/work
      - ${BUILD_PATH}:/build
      - ./docker/nginx/logs:/var/log/nginx/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: ./docker/node
    ports:
      - 8880:8880
      - 13000:13000
    volumes:
      - ${PROJECT_PATH}:/work
      - ${BUILD_PATH}:/build
    working_dir: /work
